### ISSUE TITLE
Schedule instance stop/start time

### ISSUE THREAD

**Issue by sbower** [CU-CloudCollab/aws-gaps#1]
Currently there is no built in function to stop/start instances on a schedule.  Our group has scripts combined with Jenkins to accomplish this.  Need to review and document solution.

**Comment by sr523** [comment]
Here is a brief example of how to do this from ruby sdk .. this will start and stop ec2 instances based tags .. like shawn, we hook this into a tool like jenkins

https://gist.github.com/sross07/3d8fdd1e9deda47fd907

**Comment by sbower** [comment]
This looks good.  Could you add to the aws-examples library and write up something on the on the wiki for this?

**Comment by sr523** [comment]
added to aws-examples library & lambda statement to do a similar task
