### ISSUE TITLE
Automate growing size of root EBS volume

### ISSUE THREAD

**Issue by sbower** [CU-CloudCollab/aws-gaps#10]
Currently in order to grow the size of a root EBS volume you must AMI the instance then relaunch the instance with a larger size for the rooot volume.  It would be nice to automate this process.

**Comment by nl85cit** [comment]
Initial Steps to Solve problem: 
1.) Get instance ID, Get Volume ID
2.) STOP instance
3.) Snapshot volume ( get snapshot ID ) 
4.) Detach Root volume ( get volumeID ) to instance
5.) Create new volume ( $size ) - based on snap-shot ( get new volumeID)  ( create volume namt ) 
6.) Attache new volume to instance ( mount point is "/dev/xvda"  "/dev/xvda" ) 
7.) start instance
8.) script to resize2fs

**Comment by paul-e-allen** [comment]
This issue is solved in https://github.com/CU-CloudCollab/ebs-expand-root-vol
