### ISSUE TITLE
Find latest EBS snapshot

### ISSUE THREAD

**Issue by sbower** [CU-CloudCollab/aws-gaps#11]
It would be nice to have an API call to find the latest (by date) EBS snapshot given a specific search criteria.

**Comment by ds269** [comment]
As part of the spring 2016 Cornell Hackathon, our team worked on this issue, combined with AWS gaps issue #12 . A working solution was developed and later refactored. The solution is available here: https://github.com/CU-CloudCollab/ebs-restore
