### ISSUE TITLE
Scheduled lambda function to autokill resources based on tag

### ISSUE THREAD

**Issue by paul-e-allen** [CU-CloudCollab/aws-gaps#29]
A scheduled lambda function could search an AWS account for provisioned resources labelled with something like "autokill=X" and that function could terminate/free so-labelled resources resources if they have been running more than X hours. 

This allows an easy way for developers/testers to ensure that test/play resources are disposed of, without having to remember it. Of course, they'd still have to remember to label it properly.

An option/variant could simply send emails about resources that are past their autokill date.

An option/variant could simply stop instances instead of terminating them.

**Comment by sr523** [comment]
To add onto this,  a lambda function that turns resources on/off (start/stop)  based on a specific tag .. to be used in the use case when we want instances to be off from 6pm to 6am because they are non-production

**Comment by paul-e-allen** [comment]
Ideas for label structure:
- Label name: **lifecycle-policy**
- Label value formats:
  - **limit-stop:[h]**
    - Stop the instance if it is running and if more than [h] hours have elapsed since instance launch date/time.
    - special case "limit-stop:0" means to stop as soon as possible.
  - **limit-terminate:[h]**
    - Terminate the instance (or destroy the resource) if more than [h] hours have elapsed since instance launch date/time.
  - **limit-email:[h],[email-address]**
    - Send an email to [email-address] if more than [h] hours have elapsed since instance launch date/time.
  - **cycle-daily:[on-hour],[off-hour]**
    - Cycle this instance daily, turning it on at [on-hour] and off at [off-hour]. Hour values are 0-23 and are relative to the local time of the AWS region.
    - If [on-hour] > [off-hour] then this is interpreted that the instance should be running over night. E.g., 20,04 would target to turn on the instance at 8pm and off at 4am.
    - If [on-hour] == [off-hour], the policy is non-sensical and nothing is done.
  - **cycle-weekday:[on-hour],[off-hour]**
    - Cycle this instance on weekdays, turning it on at [on-hour] and off at [off-hour]. Hour values are 0-23 and are relative to the local time of the AWS region. Instances remain off on weekends.
    - If [on-hour] > [off-hour], these are invalid parameters.
    - If [on-hour] == [off-hour], the policy is nonsensical and nothing is done.

Q: Is there some way to leverage cron scheduling format, which many people would be familiar with.

**Comment by sr523** [comment]
Responding to your question... 
You can setup lambda events to use cron expressions: http://docs.aws.amazon.com/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html

**Comment by ericgrysko** [comment]
fwiw - CloudWatch Events rules can also be scheduled with a cron expression and target a lambda. 

There might be something clever there with combining cloudwatch event on instance start w/SQS + lambda.

**Comment by paul-e-allen** [comment]
Implemented in https://github.com/CU-CloudCollab/aws-manage-lifecycles.
