### ISSUE TITLE
Automatic tagging

### ISSUE THREAD

**Issue by sbower** [CU-CloudCollab/aws-gaps#6]
When resources are created it would be ideal to apply some metadata (tags) to that resource.  This could be accomplish through a lambda function I think.

**Comment by paul-e-allen** [comment]
This one may be largely solved: https://blogs.aws.amazon.com/security/post/Tx150Z810KS4ZEC/How-to-Automatically-Tag-Amazon-EC2-Resources-in-Response-to-API-Events

**Comment by paul-e-allen** [comment]
The Cloud Formation template in that post works as expected, however the order of the elements in the CF template caused an error. The attached file fixes that issue.
[autotag template.txt](https://github.com/CU-CloudCollab/aws-gaps/files/348525/autotag.template.txt)

**Comment by paul-e-allen** [comment]
The Cloud Formation template in that post works as expected, however the order of the elements in the CF template caused an error. The attached file fixes that issue.

[autotag.template.txt](https://github.com/CU-CloudCollab/aws-gaps/files/348526/autotag.template.txt)

**Comment by paul-e-allen** [comment]
For a "cost-center" tag, which resource types would we want to catch and tag?
See http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-how.html

**Comment by philiprobinson** [comment]
Theoretically all of them, though the lion’s share of our costs are EC2 (65% for June) and RDS (28.8%).

Phil

**Comment by paul-e-allen** [comment]
Created [aws-autotag repo](https://github.com/CU-CloudCollab/aws-autotag) containing CloudFormation template to create example Lambda function to tag EC2 resources.
