### ISSUE TITLE
Automated way to pre-warm EBS volumes

### ISSUE THREAD

**Issue by sbower** [CU-CloudCollab/aws-gaps#9]
When an EBS volume is created if there is going to be heavy use the volume should be pre-warmed.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html

**Comment by ericgrysko** [comment]
@sbower since AWS has changed their stance on need for pre-warming, can we close this one out?

**Comment by sbower** [comment]
yup makes sense to me
